banner_template = {
    'ARM': '',
    'Borrower First Name': '',
    'Borrower Last Name': '',
    'Delivery Method': '',
    'Job Identifier': '',
    'Loan#': '',
    'NY Properties': '',
    'Property Address City': '',
    'Property Address Line 1': '',
    'Property Address Line 2': '',
    'Property Address State': '',
    'Property Address Zip': '',
    'Return Label Address Attention': '',
    'Return Label Address City': '',
    'Return Label Address Line 1': '',
    'Return Label Address Line 2': '',
    'Return Label Address Phone': '',
    'Return Label Address Plus4': '',
    'Return Label Address State': '',
    'Return Label Address Zip': '',
    'Ship From Address Attention': '',
    'Ship From Address City': '',
    'Ship From Address Line 1': '',
    'Ship From Address Line 2': '',
    'Ship From Address Phone': '',
    'Ship From Address Plus4': '',
    'Ship From Address State': '',
    'Ship From Address Zip': '',
    'Ship To Address Attention': '',
    'Ship To Address City': '',
    'Ship To Address Line 1': '',
    'Ship To Address Line 2': '',
    'Ship To Address Phone': '',
    'Ship To Address Plus4': '',
    'Ship To Address State': '',
    'Ship To Address Zip': '',
    'Your Home Loan Toolkit': '',
}
